/**
 * Ask Lumen v2 — branded PDF export for the chat `generate_pdf` tool.
 *
 * Flow: model calls generate_pdf({title, language, sections}) -> we render a
 * branded light-theme HTML report -> Cloudflare Browser Rendering (env.BROWSER)
 * prints it to a true vector A4 PDF -> stored in R2 under
 * patients/{id}/chat-exports/{uuid}.pdf -> we mint an HMAC-signed, time-limited
 * token and hand back a /api/chat/v2/export/{token} URL for the model to present.
 *
 * R2 object-level expiry is enforced two ways: the download token carries a hard
 * 7-day max expiry (so links die), and each object stores an `expires_at`
 * customMetadata value. Configure a bucket lifecycle rule on the prefix
 * `patients/` (chat-exports/) in the Cloudflare dashboard to hard-delete the
 * blobs — the Pages deploy token can't manage R2 lifecycle.
 */

const EXPORT_TTL_MS = 7 * 24 * 3600 * 1000; // 7 days

/* ───── tiny, safe markdown -> HTML (bold, headings, lists, paragraphs) ───── */
function esc(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function inlineMd(s) {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}
function bodyMdToHtml(md) {
  const lines = String(md || "").split(/\r?\n/);
  const html = [];
  let list = null; // 'ul' | 'ol'
  const closeList = () => { if (list) { html.push(`</${list}>`); list = null; } };
  for (const raw of lines) {
    const line = raw.trimEnd();
    let m;
    if (!line.trim()) { closeList(); continue; }
    if ((m = /^(#{1,3})\s+(.*)$/.exec(line))) { closeList(); html.push(`<h${m[1].length + 2}>${inlineMd(m[2])}</h${m[1].length + 2}>`); continue; }
    if ((m = /^\s*[-*]\s+(.*)$/.exec(line))) { if (list !== "ul") { closeList(); html.push("<ul>"); list = "ul"; } html.push(`<li>${inlineMd(m[1])}</li>`); continue; }
    if ((m = /^\s*\d+[.)]\s+(.*)$/.exec(line))) { if (list !== "ol") { closeList(); html.push("<ol>"); list = "ol"; } html.push(`<li>${inlineMd(m[1])}</li>`); continue; }
    closeList(); html.push(`<p>${inlineMd(line)}</p>`);
  }
  closeList();
  return html.join("\n");
}

/**
 * Build the branded HTML document.
 * @param {{title:string, language?:string, sections:Array<{heading:string, body_markdown:string}>}} doc
 */
export function buildChatPdfHtml(doc) {
  const lang = doc.language === "pt" ? "pt" : "en";
  const generated = lang === "pt" ? "Gerado pelo Lumen Health" : "Generated by Lumen Health";
  const disclaimer = lang === "pt"
    ? "Este documento ajuda você a se preparar para o seu médico — ele não fornece diagnósticos médicos."
    : "This document helps you prepare for your doctor — it does not provide medical diagnoses.";
  const sections = (doc.sections || []).map((s) => `
    <section class="rpt-section">
      <h2>${esc(s.heading || "")}</h2>
      <div class="rpt-body">${bodyMdToHtml(s.body_markdown || "")}</div>
    </section>`).join("\n");

  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8">
<style>
  @page { size: A4; margin: 22mm 18mm; }
  :root { --navy:#0D1B33; --gold:#B8860B; --ink:#1b2a3d; --muted:#5a6b7e; --line:#e3e0d6; --bg:#ffffff; }
  * { box-sizing: border-box; }
  body { font-family:'IBM Plex Sans', -apple-system, system-ui, sans-serif; color:var(--ink); background:var(--bg); margin:0; line-height:1.5; }
  .rpt-head { border-bottom:3px solid var(--gold); padding-bottom:14px; margin-bottom:26px; }
  .rpt-brand { font-family:'IBM Plex Mono', monospace; font-size:11px; letter-spacing:.18em; text-transform:uppercase; color:var(--gold); }
  h1 { font-family:'Raleway', sans-serif; font-weight:700; color:var(--navy); font-size:26px; margin:6px 0 4px; }
  .rpt-meta { font-family:'IBM Plex Mono', monospace; font-size:11px; color:var(--muted); }
  h2 { font-family:'Raleway', sans-serif; font-weight:700; color:var(--navy); font-size:16px; margin:24px 0 8px; padding-bottom:5px; border-bottom:1px solid var(--line); }
  h3,h4,h5 { font-family:'Raleway', sans-serif; color:var(--navy); margin:14px 0 4px; font-size:13px; }
  .rpt-section { break-inside: avoid; page-break-inside: avoid; }
  .rpt-body p { margin:6px 0; }
  ul, ol { margin:6px 0 6px 20px; padding:0; }
  li { margin:3px 0; }
  strong { color:var(--navy); }
  code { font-family:'IBM Plex Mono', monospace; font-size:12px; background:#f5f3ec; padding:1px 4px; border-radius:3px; }
  .rpt-foot { margin-top:30px; padding-top:12px; border-top:1px solid var(--line); font-size:10px; color:var(--muted); }
</style></head>
<body>
  <header class="rpt-head">
    <div class="rpt-brand">Lumen Health</div>
    <h1>${esc(doc.title || (lang === "pt" ? "Resumo de saúde" : "Health summary"))}</h1>
    <div class="rpt-meta">${generated}</div>
  </header>
  ${sections}
  <footer class="rpt-foot">${esc(disclaimer)}</footer>
</body></html>`;
}

/** Render HTML to A4 PDF bytes via Browser Rendering. Lazy-imports puppeteer. */
export async function renderChatPdf(env, doc) {
  const { default: puppeteer } = await import("@cloudflare/puppeteer");
  const browser = await puppeteer.launch(env.BROWSER);
  try {
    const page = await browser.newPage();
    await page.setContent(buildChatPdfHtml(doc), { waitUntil: "networkidle0" });
    return await page.pdf({ format: "A4", printBackground: true });
  } finally {
    await browser.close();
  }
}

/* ───── HMAC-signed, time-limited download tokens ───── */
function b64urlEncode(bytes) {
  let bin = "";
  const u8 = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  for (const b of u8) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function b64urlDecode(str) {
  const s = str.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((str.length + 3) % 4);
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
async function hmacKey(env) {
  if (!env.CHAT_EXPORT_SIGNING_KEY) throw new Error("CHAT_EXPORT_SIGNING_KEY not configured");
  return crypto.subtle.importKey("raw", new TextEncoder().encode(env.CHAT_EXPORT_SIGNING_KEY),
    { name: "HMAC", hash: "SHA-256" }, false, ["sign", "verify"]);
}

/** @param {{patientId:string, key:string, exp:number}} payload */
export async function signExportToken(env, payload) {
  const key = await hmacKey(env);
  const body = b64urlEncode(new TextEncoder().encode(JSON.stringify(payload)));
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(body));
  return `${body}.${b64urlEncode(sig)}`;
}

/** Returns the validated payload or null. Enforces signature + expiry. */
export async function verifyExportToken(env, token) {
  try {
    const [body, sig] = String(token || "").split(".");
    if (!body || !sig) return null;
    const key = await hmacKey(env);
    const ok = await crypto.subtle.verify("HMAC", key, b64urlDecode(sig), new TextEncoder().encode(body));
    if (!ok) return null;
    const payload = JSON.parse(new TextDecoder().decode(b64urlDecode(body)));
    if (!payload?.exp || Date.now() > payload.exp) return null;
    return payload;
  } catch { return null; }
}

/**
 * Render -> store in R2 -> return a presentable download descriptor.
 * @returns {Promise<{url:string, filename:string, size:number, key:string, exp:number}>}
 */
export async function createChatPdfExport(env, { patientId, doc, origin }) {
  if (!env.R2_BUCKET) throw new Error("R2_BUCKET binding missing");
  const pdf = await renderChatPdf(env, doc);
  const id = crypto.randomUUID();
  const key = `patients/${patientId}/chat-exports/${id}.pdf`;
  const exp = Date.now() + EXPORT_TTL_MS;
  const safeTitle = String(doc.title || "lumen-health").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "summary";
  const filename = `lumen-${safeTitle}.pdf`;

  await env.R2_BUCKET.put(key, pdf, {
    httpMetadata: { contentType: "application/pdf", contentDisposition: `attachment; filename="${filename}"` },
    customMetadata: { patient_id: patientId, expires_at: new Date(exp).toISOString() },
  });

  const token = await signExportToken(env, { patientId, key, exp });
  return { url: `${origin}/api/chat/v2/export/${token}`, filename, size: pdf.length ?? pdf.byteLength ?? 0, key, exp };
}

/** Serve a previously-exported PDF given a signed token. */
export async function serveChatExport(env, token) {
  const payload = await verifyExportToken(env, token);
  if (!payload) return new Response("link expired or invalid", { status: 403 });
  const obj = await env.R2_BUCKET.get(payload.key);
  if (!obj) return new Response("not found", { status: 404 });
  const filename = (payload.key.split("/").pop() || "export.pdf");
  return new Response(obj.body, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": obj.httpMetadata?.contentDisposition || `attachment; filename="${filename}"`,
      "Cache-Control": "private, no-store",
    },
  });
}
