/**
 * Server-rendered dark COVER page for the PDF export ("/print" route).
 *
 * Why only the cover is server-rendered: the app's section renderers live in
 * web/assets/patient-context.js as a strict IIFE that self-renders whole pages
 * into document.body — they cannot be invoked from a standalone document. So the
 * content pages are captured client-side from the real section pages (the proven
 * export.js technique), while the cover — which carries patient PHI and benefits
 * from no client data shape — is rendered here, server-side, behind the opaque
 * HMAC token. This keeps PHI out of the URL (acceptance: "No PHI in URLs").
 *
 * Pure string builder: no DB / IO. The Worker fetches patient meta + counts,
 * verifies the token, then calls buildCoverDocument().
 */

import { leafLabel } from "./export-manifest.js";

const esc = (s) =>
  String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

const STR = {
  confidentialKicker: { en: "CONFIDENTIAL HEALTH REPORT", pt: "RELATÓRIO DE SAÚDE CONFIDENCIAL" },
  tagline: { en: "FROM SCATTERED DATA TO INSIGHTS", pt: "DE DADOS DISPERSOS A INSIGHTS" },
  patient: { en: "Patient", pt: "Paciente" },
  dob: { en: "Date of birth", pt: "Data de nascimento" },
  sex: { en: "Sex", pt: "Sexo" },
  patientId: { en: "Patient ID", pt: "ID do paciente" },
  care: { en: "Care / clinician", pt: "Cuidado / clínico" },
  generated: { en: "Generated", pt: "Gerado em" },
  language: { en: "Language", pt: "Idioma" },
  includes: { en: "Includes", pt: "Inclui" },
  langName: { en: "English", pt: "Português (BR)" },
  disclaimer: {
    en: "CONFIDENTIAL. This report contains protected health information generated by Lumen Health from data supplied by the patient. It is intended solely for the named patient and the clinicians they choose to share it with. It is a summary for discussion and is not a diagnosis. Verify all values against source records.",
    pt: "CONFIDENCIAL. Este relatório contém informações de saúde protegidas, geradas pela Lumen Health a partir de dados fornecidos pelo paciente. Destina-se exclusivamente ao paciente nomeado e aos clínicos com quem ele opte por compartilhá-lo. É um resumo para discussão e não constitui um diagnóstico. Verifique todos os valores nos registros de origem.",
  },
  notProvided: { en: "—", pt: "—" },
};

/** Localised long date: "6 June 2026" / "6 de junho de 2026". */
export function formatGeneratedDate(date, language) {
  const locale = language === "pt" ? "pt-BR" : "en-GB";
  try {
    return new Intl.DateTimeFormat(locale, { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(date);
  } catch {
    return date.toISOString().slice(0, 10);
  }
}

/** The heart + ECG logo, lifted verbatim from web/assets/logo-on-dark.svg. */
const LOGO_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" aria-label="Lumen Health" class="cover-logo">
  <g transform="translate(32, 32) scale(1.1)">
    <path d="M 0 22 C -20 6, -28 -2, -20 -14 C -12 -22, -4 -18, 0 -10 C 4 -18, 12 -22, 20 -14 C 28 -2, 20 6, 0 22 Z" fill="rgba(36, 78, 110, 0.55)" stroke="#6BA3C7" stroke-width="0.7" stroke-linejoin="round"/>
    <path d="M -36 0 L -22 0 L -16 4 L -10 -4 L -2 -16 L 6 14 L 12 -4 L 18 0 L 36 0" fill="none" stroke="#F4B942" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
</svg>`;

/**
 * Build the full standalone HTML document for the dark cover page.
 *
 * @param {object} args
 * @param {object} args.patient   { name, dob, sex, patientId, clinician }
 * @param {string[]} args.sections selected leaf ids (for the "Includes" chips)
 * @param {'en'|'pt'} args.language
 * @param {Date} args.generatedAt
 * @returns {string} HTML
 */
export function buildCoverDocument({ patient = {}, sections = [], language = "en", generatedAt = new Date() }) {
  const L = language === "pt" ? "pt" : "en";
  const t = (k) => STR[k][L];
  const dateStr = formatGeneratedDate(generatedAt, L);

  const chips = sections
    .map((id) => leafLabel(id))
    .filter(Boolean)
    .map((lbl) => `<span class="cover-chip">${esc(lbl[L])}</span>`)
    .join("");

  const row = (key, val) =>
    `<div class="cover-meta-key">${esc(key)}</div><div class="cover-meta-val">${val ? esc(val) : t("notProvided")}</div>`;

  return `<!doctype html>
<html lang="${L}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lumen Health — ${esc(t("confidentialKicker"))}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;700&family=IBM+Plex+Sans:wght@300;400;500&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root {
    --bg-page: #0A1428; --text-primary: #F0F4F8; --text-muted: #8FA3BC;
    --accent-gold: #F4B942; --accent-petrol: #6BA3C7; --border-subtle: #283655;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { background: var(--bg-page); color: var(--text-primary);
    -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  @page { size: A4; margin: 0; }
  .cover {
    position: relative; width: 210mm; min-height: 297mm; overflow: hidden;
    padding: 22mm 20mm; display: flex; flex-direction: column;
    font-family: 'IBM Plex Sans', system-ui, sans-serif;
  }
  /* subtle 64px grid at ~2.5% white (mirrors .theme-dark::before) */
  .cover::before {
    content: ''; position: absolute; inset: 0; pointer-events: none;
    background-image:
      linear-gradient(to right, rgba(255,255,255,0.025) 1px, transparent 1px),
      linear-gradient(to bottom, rgba(255,255,255,0.025) 1px, transparent 1px);
    background-size: 64px 64px;
  }
  .cover > * { position: relative; z-index: 1; }
  .mono { font-family: 'IBM Plex Mono', monospace; }
  .cover-top {
    display: flex; justify-content: space-between; align-items: flex-start;
    font-family: 'IBM Plex Mono', monospace; font-size: 9.5px; letter-spacing: 0.18em;
    text-transform: uppercase; color: var(--text-muted);
  }
  .cover-center { margin: auto 0; text-align: center; padding: 18mm 0; }
  .cover-logo { width: 92px; height: 92px; display: block; margin: 0 auto 14px; }
  .cover-brand { font-family: 'Raleway', sans-serif; font-weight: 200; font-size: 46px;
    letter-spacing: 0.02em; line-height: 1; }
  .cover-tagline { font-family: 'IBM Plex Mono', monospace; font-size: 11px;
    letter-spacing: 0.34em; text-transform: uppercase; color: var(--accent-gold);
    margin-top: 12px; }
  .cover-meta {
    display: grid; grid-template-columns: max-content 1fr; gap: 7px 22px;
    border-top: 1px solid var(--border-subtle); border-bottom: 1px solid var(--border-subtle);
    padding: 16px 0; margin-bottom: 18px;
  }
  .cover-meta-key { font-family: 'IBM Plex Mono', monospace; font-size: 10px;
    letter-spacing: 0.12em; text-transform: uppercase; color: var(--text-muted);
    align-self: center; }
  .cover-meta-val { font-size: 14px; font-weight: 400; }
  .cover-inc-label { font-family: 'IBM Plex Mono', monospace; font-size: 10px;
    letter-spacing: 0.14em; text-transform: uppercase; color: var(--text-muted);
    margin-bottom: 8px; }
  .cover-chips { display: flex; flex-wrap: wrap; gap: 7px; margin-bottom: 22px; }
  .cover-chip {
    font-family: 'IBM Plex Mono', monospace; font-size: 10.5px; letter-spacing: 0.04em;
    padding: 4px 10px; border-radius: 999px;
    background: rgba(107,163,199,0.12); color: var(--accent-petrol);
    border: 1px solid rgba(107,163,199,0.4);
  }
  .cover-disclaimer { font-size: 9.5px; line-height: 1.55; color: var(--text-muted);
    border-left: 2px solid var(--accent-gold); padding-left: 12px; margin-top: auto; }
  .cover-foot { display: flex; justify-content: space-between;
    font-family: 'IBM Plex Mono', monospace; font-size: 9px; letter-spacing: 0.1em;
    color: var(--text-muted); margin-top: 14px; }
</style>
</head>
<body>
  <section class="cover" data-export-cover>
    <div class="cover-top">
      <span>${esc(t("confidentialKicker"))}</span>
      <span>${esc(patient.patientId || "")}</span>
    </div>

    <div class="cover-center">
      ${LOGO_SVG}
      <div class="cover-brand">Lumen Health</div>
      <div class="cover-tagline">${esc(t("tagline"))}</div>
    </div>

    <div class="cover-meta">
      ${row(t("patient"), patient.name)}
      ${row(t("dob"), patient.dob)}
      ${row(t("sex"), patient.sex)}
      ${row(t("patientId"), patient.patientId)}
      ${row(t("care"), patient.clinician)}
      ${row(t("generated"), dateStr)}
      ${row(t("language"), t("langName"))}
    </div>

    ${chips ? `<div class="cover-inc-label">${esc(t("includes"))}</div><div class="cover-chips">${chips}</div>` : ""}

    <p class="cover-disclaimer">${esc(t("disclaimer"))}</p>

    <div class="cover-foot">
      <span>lumenhealth.io</span>
      <span>${esc(dateStr)}</span>
    </div>
  </section>
  <script>window.__lxReady = true;</script>
</body>
</html>`;
}
