/* GENERATED by scripts/extract-bespoke-context.mjs — do not edit by hand.
   Source of truth: web/assets/patient-context.js (PAULO_STUDIES). Re-run the extractor after editing that asset. */
export default {
  "studies": [
    {
      "slug": "paulo-cervical-mri-2026-05-15",
      "labelEn": "2A · MRI · Cervical spine",
      "labelPt": "2A · RM · Coluna cervical",
      "titleEn": "MRI cervical spine · 15 May 2026",
      "titlePt": "RM da coluna cervical · 15 de maio de 2026",
      "blurbEn": "MRI of the cervical spine without intravenous contrast. Three orientations were acquired — axial T2 (35 slices), coronal T2 (12) and sagittal (45, across T1 / T2 / STIR weightings, grouped in that order on the slider). Use the AXI / COR / SAG buttons inside the viewer to switch plane, then scrub the slider to walk through the slices.",
      "blurbPt": "Ressonância da coluna cervical sem contraste endovenoso. Três orientações adquiridas — axial T2 (35 cortes), coronal T2 (12) e sagital (45, com sequências T1 / T2 / STIR, agrupadas nessa ordem ao longo do slider). Use os botões AXI / COR / SAG no visualizador para alternar o plano e depois deslize o controle para percorrer os cortes.",
      "pdfHref": "scans/paulo-cervical-mri-2026-05-15-report.pdf",
      "pdfLabelEn": "Export cervical MRI report (PDF)",
      "pdfLabelPt": "Exportar laudo da RM cervical (PDF)",
      "identsEn": [
        "<strong>Patient.</strong> Paulo Augusto Silotto Dias de Souza",
        "<strong>DOB.</strong> 14 July 1961",
        "<strong>Exam date.</strong> 15 May 2026",
        "<strong>Exam.</strong> MRI cervical spine",
        "<strong>Accession.</strong> 5463652",
        "<strong>Reporting physician.</strong> Dr. Marco Antonio de Carvalho · CRM-99607",
        "<strong>Provider.</strong> CETAM Diagnóstico",
        "<strong>Insurance.</strong> Bradesco Saúde"
      ],
      "identsPt": [
        "<strong>Paciente.</strong> Paulo Augusto Silotto Dias de Souza",
        "<strong>Data de nascimento.</strong> 14 de julho de 1961",
        "<strong>Data do exame.</strong> 15 de maio de 2026",
        "<strong>Exame.</strong> RM da coluna cervical",
        "<strong>Identificador.</strong> 5463652",
        "<strong>Médico responsável.</strong> Dr. Marco Antonio de Carvalho · CRM-99607",
        "<strong>Prestador.</strong> CETAM Diagnóstico",
        "<strong>Convênio.</strong> Bradesco Saúde"
      ],
      "techniqueEn": [
        "Multi-planar acquisition in T1, T2 and STIR weighted sequences.",
        "No paramagnetic intravenous contrast administered."
      ],
      "techniquePt": [
        "Aquisição multiplanar em sequências ponderadas em T1, T2 e STIR.",
        "Sem administração de contraste endovenoso paramagnético."
      ],
      "findingsEn": [
        "Cranio-vertebral junction structures without abnormalities.",
        "Sinistroconvex deviation of the axis in the position of study.",
        "Vertebral bodies aligned, with normal height and marginal osteophytes.",
        "Posterior elements intact. Arthrosis of the uncovertebral and facet joints, more evident at the lower cervical levels, with diffuse thickening of the ligamentum flavum.",
        "Signs of diffuse disc dehydration predominating at <strong>C6–C7</strong>, where reduced disc height is observed.",
        "Mild disc bulging at <strong>C3–C4 and C4–C5</strong> that flattens the ventral aspect of the dural sac and mildly reduces the bilateral foraminal dimensions.",
        "Diffuse disco-osteophytic bulging at <strong>C5–C6</strong> that compresses the ventral aspect of the spinal cord, without myelopathy, and reduces the bilateral foraminal dimensions, contacting the respective exiting nerve roots.",
        "Spinal cord with normal morphology and signal intensity.",
        "Mild hypotrophy of the paravertebral musculature, predominating in the lumbosacral region."
      ],
      "findingsPt": [
        "Estruturas da junção crânio-vertebral sem anormalidades.",
        "Desvio sinistro-convexo do eixo na posição do estudo.",
        "Corpos vertebrais alinhados, com altura normal e osteófitos marginais.",
        "Elementos posteriores íntegros. Artrose das uncovertebrais e interapofisárias, mais evidente nos níveis cervicais inferiores, com espessamento difuso do ligamento amarelo.",
        "Sinais de hipohidratação discal difusa predominando em <strong>C6–C7</strong>, onde se observa redução da altura discal.",
        "Abaulamento discal discreto de <strong>C3–C4 e C4–C5</strong> que retifica a face ventral do saco dural e reduz discretamente as amplitudes foraminais bilaterais.",
        "Abaulamento disco-osteofitário difuso de <strong>C5–C6</strong> que comprime a face ventral da medula, sem mielopatia, e reduz as amplitudes foraminais bilaterais tocando as respectivas emergentes.",
        "Medula de morfologia e intensidade de sinal normais.",
        "Discreta hipotrofia da musculatura paravertebral predominando na região lombossacra."
      ],
      "conclusionEn": "<strong>Impression:</strong> Multilevel cervical degenerative change. Mild C3–C4 and C4–C5 disc bulging with shallow bilateral foraminal narrowing. <strong>Diffuse C5–C6 disco-osteophytic bulging with ventral cord compression — no myelopathy</strong> — and bilateral foraminal narrowing contacting both exiting roots. Sinistroconvex deviation of the cervical axis and mild paravertebral muscle hypotrophy.",
      "conclusionPt": "<strong>Conclusão:</strong> Alterações degenerativas cervicais multinivelares. Abaulamento discal discreto em C3–C4 e C4–C5 com redução foraminal bilateral. <strong>Abaulamento disco-osteofitário difuso em C5–C6 com compressão ventral da medula — sem mielopatia</strong> — e redução foraminal bilateral tocando ambas as emergentes. Desvio sinistro-convexo do eixo cervical e hipotrofia discreta da musculatura paravertebral."
    },
    {
      "slug": "paulo-lombar-mri-2026-05-15",
      "labelEn": "2B · MRI · Lumbar spine",
      "labelPt": "2B · RM · Coluna lombar",
      "titleEn": "MRI lumbar spine · 15 May 2026",
      "titlePt": "RM da coluna lombar · 15 de maio de 2026",
      "blurbEn": "MRI of the lumbar spine without intravenous contrast. Three orientations were acquired — axial T2 (25 slices), coronal T2 (12) and sagittal (48, across STIR / T2 CLEAR / T1 weightings, grouped in that order on the slider). Use the AXI / COR / SAG buttons inside the viewer to switch plane, then scrub the slider to walk through the slices.",
      "blurbPt": "Ressonância da coluna lombar sem contraste endovenoso. Três orientações adquiridas — axial T2 (25 cortes), coronal T2 (12) e sagital (48, com sequências STIR / T2 CLEAR / T1, agrupadas nessa ordem ao longo do slider). Use os botões AXI / COR / SAG no visualizador para alternar o plano e depois deslize o controle para percorrer os cortes.",
      "pdfHref": "scans/paulo-lombar-mri-2026-05-15-report.pdf",
      "pdfLabelEn": "Export lumbar MRI report (PDF)",
      "pdfLabelPt": "Exportar laudo da RM lombar (PDF)",
      "identsEn": [
        "<strong>Patient.</strong> Paulo Augusto Silotto Dias de Souza",
        "<strong>DOB.</strong> 14 July 1961",
        "<strong>Exam date.</strong> 15 May 2026",
        "<strong>Exam.</strong> MRI lumbar spine",
        "<strong>Accession.</strong> 5463652",
        "<strong>Reporting physician.</strong> Dr. Marco Antonio de Carvalho · CRM-99607",
        "<strong>Provider.</strong> CETAM Diagnóstico",
        "<strong>Insurance.</strong> Bradesco Saúde"
      ],
      "identsPt": [
        "<strong>Paciente.</strong> Paulo Augusto Silotto Dias de Souza",
        "<strong>Data de nascimento.</strong> 14 de julho de 1961",
        "<strong>Data do exame.</strong> 15 de maio de 2026",
        "<strong>Exame.</strong> RM da coluna lombar",
        "<strong>Identificador.</strong> 5463652",
        "<strong>Médico responsável.</strong> Dr. Marco Antonio de Carvalho · CRM-99607",
        "<strong>Prestador.</strong> CETAM Diagnóstico",
        "<strong>Convênio.</strong> Bradesco Saúde"
      ],
      "techniqueEn": [
        "Multi-planar acquisition in T1, T2 and STIR weighted sequences.",
        "No paramagnetic intravenous contrast administered."
      ],
      "techniquePt": [
        "Aquisição multiplanar em sequências ponderadas em T1, T2 e STIR.",
        "Sem administração de contraste endovenoso paramagnético."
      ],
      "findingsEn": [
        "Sinistroconvex deviation of the axis in the position of study. Flattening of the physiological lumbar curvature.",
        "Mild anterolisthesis of <strong>L3 over L4</strong>. Minimal retrolisthesis of <strong>L1 over L2</strong>.",
        "Vertebral bodies with normal height and marginal osteophytes.",
        "Diffuse disc dehydration and reduction in disc heights.",
        "Degenerative discopathy at <strong>L1–L2, L2–L3 and L4–L5</strong> with irregularity of the opposing endplates and <strong>Modic I (oedema)</strong> signal changes at the three levels, and <strong>Modic II (fatty)</strong> at L4–L5.",
        "Mild disc bulging at <strong>L1–L2</strong> that flattens the ventral aspect of the dural sac and reduces the bilateral foraminal dimensions, notably on the left.",
        "Diffuse disc bulging at <strong>L2–L3</strong> that compresses the ventral aspect of the dural sac, contacts the anterior descending roots, and reduces the bilateral foraminal dimensions with <strong>stenosis and compression of the exiting root on the left</strong>.",
        "Diffuse disc pseudo-bulging at <strong>L3–L4</strong> that compresses the ventral aspect of the dural sac and, combined with facet joint hypertrophy and ligamentum flavum thickening, produces <strong>spinal canal stenosis</strong> with compression of the anterior descending roots and bilateral reduction of foraminal dimensions, notably on the left, contacting the respective exiting root.",
        "Diffuse disco-osteophytic bulging at <strong>L4–L5</strong> with a protruding central disc component that compresses the ventral aspect of the dural sac, contacting the bilateral anterior descending roots, and reduces the foraminal dimensions, contacting the right exiting root.",
        "<strong>Left paramedian / foraminal disc extrusion at L5–S1</strong> which, combined with ipsilateral facet hypertrophy, compresses the ipsilateral S1 descending root.",
        "Conus medullaris and cauda equina in normal topographic position, with normal morphology and signal intensity.",
        "Moderate hypotrophy of the paravertebral musculature.",
        "Oedema of the interspinous ligament at <strong>L2–L3, L3–L4 and L5–S1</strong>."
      ],
      "findingsPt": [
        "Desvio sinistro-convexo do eixo na posição do estudo. Retificação da curvatura lombar fisiológica.",
        "Anterolistese discreta de <strong>L3 sob L4</strong>. Mínima retrolistese de <strong>L1 sobre L2</strong>.",
        "Corpos vertebrais com altura normal e osteófitos marginais.",
        "Hipohidratação e redução difusa das alturas discais.",
        "Discopatia degenerativa de <strong>L1–L2, L2–L3 e L4–L5</strong> com irregularidade dos platôs apostos e alteração de sinal do tipo <strong>Modic I (edema)</strong> nos três níveis e <strong>Modic II (gordura)</strong> em L4–L5.",
        "Abaulamento discal discreto de <strong>L1–L2</strong> que retifica a face ventral do saco dural e reduz as amplitudes foraminais bilaterais, notadamente à esquerda.",
        "Abaulamento discal difuso de <strong>L2–L3</strong> que comprime a face ventral do saco dural, toca as descendentes anteriores e reduz as amplitudes foraminais bilaterais com <strong>estenose e compressão da emergente à esquerda</strong>.",
        "Pseudo-abaulamento discal difuso de <strong>L3–L4</strong> que comprime a face ventral do saco dural e, associado à hipertrofia das interfacetárias e espessamento dos ligamentos amarelos, determina <strong>estenose do canal vertebral</strong>, com compressão das descendentes anteriores e redução das amplitudes foraminais bilaterais, notadamente à esquerda, tocando a respectiva emergente.",
        "Abaulamento disco-osteofitário difuso de <strong>L4–L5</strong> com componente discal protruso central, que comprime a face ventral do saco dural, toca as descendentes anteriores bilaterais e reduz as amplitudes foraminais tocando a emergente direita.",
        "<strong>Extrusão discal paramediana / foraminal esquerda em L5–S1</strong> que, associada à hipertrofia da facetária ipsilateral, comprime a respectiva descendente ipsilateral de S1.",
        "Cone medular e cauda equina tópicos, de morfologia e intensidade de sinal normais.",
        "Moderada hipotrofia da musculatura paravertebral.",
        "Edema do ligamento interespinhoso de <strong>L2–L3, L3–L4 e L5–S1</strong>."
      ],
      "conclusionEn": "<strong>Impression:</strong> Diffuse multisegmental degenerative spondylodiscopathy. Spinal canal stenosis at L3–L4 with anterior descending root compression; <strong>foraminal disc extrusion at L5–S1 compressing the left S1 root</strong>; bilateral foraminal narrowing throughout the lumbar segments, more severe on the left. Sinistroconvex deviation of the axis, mild L3 anterolisthesis over L4, moderate paravertebral muscle hypotrophy, and interspinous ligament oedema at L2–L3, L3–L4 and L5–S1.",
      "conclusionPt": "<strong>Conclusão:</strong> Espondilodiscopatia degenerativa difusa e multissegmentar. Estenose do canal vertebral em L3–L4 com compressão das descendentes anteriores; <strong>extrusão discal foraminal em L5–S1 comprimindo a raiz S1 esquerda</strong>; estreitamento foraminal bilateral em todo o segmento lombar, mais acentuado à esquerda. Desvio sinistro-convexo do eixo, anterolistese discreta de L3 sobre L4, hipotrofia moderada da musculatura paravertebral e edema do ligamento interespinhoso em L2–L3, L3–L4 e L5–S1."
    }
  ]
};
