/* GENERATED by scripts/extract-bespoke-context.mjs — do not edit by hand.
   Source of truth: web/assets/silvana-labs.js (labs) + web/assets/patient-context.js (inbody). Re-run the extractor after editing that asset. */
export default {
  "labs": {
    "patient": {
      "full_name": "Silvana Aparecida Creste Dias de Souza",
      "dob": "1967-09-29",
      "sex": "female",
      "country": "BR",
      "native_language": "pt"
    },
    "documents": [
      {
        "date": "2026-04-25",
        "laboratory": "Lab. Behring",
        "doctor": "Dr. Laerte Coelho Filho",
        "pdf": "silvana-source-pdfs/exames_dr_laerte.pdf",
        "title_en": "Comprehensive panel — Dr. Laerte (25 Apr 2026)",
        "title_pt": "Painel completo — Dr. Laerte (25 abr 2026)"
      },
      {
        "date": "2026-04-13",
        "laboratory": "Fleury · Ribeirão Preto",
        "doctor": "Dra. Elisabete Pinheiro Ferreira Pires",
        "pdf": "silvana-source-pdfs/silvana_creste.pdf",
        "title_en": "Hormones & liver — Dra. Elisabete (13 Apr 2026)",
        "title_pt": "Hormônios & fígado — Dra. Elisabete (13 abr 2026)"
      },
      {
        "date": "2026-03-27",
        "laboratory": "Lab. Behring",
        "doctor": null,
        "pdf": "silvana-source-pdfs/exames_deamina_oxidade_e_tsh.pdf",
        "title_en": "TSH & DAO (histamine) — 27 Mar 2026",
        "title_pt": "TSH & DAO (histamina) — 27 mar 2026"
      },
      {
        "date": "2026-02-18",
        "laboratory": "Lab. Behring",
        "doctor": "Dr. José Roberto Chodraui",
        "pdf": "silvana-source-pdfs/document_3.pdf",
        "title_en": "Comprehensive panel — Dr. Chodraui (18 Feb 2026)",
        "title_pt": "Painel completo — Dr. Chodraui (18 fev 2026)"
      },
      {
        "date": "2025-12-12",
        "laboratory": "Lab. Behring",
        "doctor": "Dra. Janaina Michelle Lima Melo",
        "pdf": "silvana-source-pdfs/dr_janaiana_alergia.pdf",
        "title_en": "Allergy workup — Dra. Janaina (12 Dec 2025)",
        "title_pt": "Investigação alérgica — Dra. Janaina (12 dez 2025)"
      },
      {
        "date": "2025-10-24",
        "laboratory": "Lab. Behring",
        "doctor": "Dr. Ricardo Menon Nose",
        "pdf": "silvana-source-pdfs/dr_ricardo_olho_seco.pdf",
        "title_en": "Autoimmune / dry-eye workup — Dr. Ricardo (24 Oct 2025)",
        "title_pt": "Investigação autoimune / olho seco — Dr. Ricardo (24 out 2025)"
      },
      {
        "date": "2025-01-22",
        "laboratory": "Lab. Behring",
        "doctor": null,
        "pdf": "silvana-source-pdfs/acido_urico.pdf",
        "title_en": "Uric acid — 22 Jan 2025",
        "title_pt": "Ácido úrico — 22 jan 2025"
      },
      {
        "date": "2024-07-24",
        "laboratory": "Lab. Behring",
        "doctor": "Dr. Luiz Augusto Guimarães de Souza",
        "pdf": "silvana-source-pdfs/dr._luis_augusto.pdf",
        "title_en": "CBC + chem + coag — Dr. Luiz Augusto (24 Jul 2024)",
        "title_pt": "Hemograma + bioquímica + coagulação — Dr. Luiz Augusto (24 jul 2024)"
      },
      {
        "date": "2024-02-27",
        "laboratory": "Lab. Behring",
        "doctor": "Dr. Ricardo Martinuzzo",
        "pdf": "silvana-source-pdfs/openpdf.pdf",
        "title_en": "Lipids + thyroid + hormones — Dr. Martinuzzo (27 Feb 2024)",
        "title_pt": "Lipídios + tireoide + hormônios — Dr. Martinuzzo (27 fev 2024)"
      },
      {
        "date": "2023-02-16",
        "laboratory": "Lab. ICD · Ribeirão Preto",
        "doctor": "Dr. Humberto Jorge Isaac",
        "pdf": "silvana-source-pdfs/resultado841179.pdf",
        "title_en": "Comprehensive follow-up — Dr. Isaac (16 Feb 2023)",
        "title_pt": "Acompanhamento — Dr. Isaac (16 fev 2023)"
      },
      {
        "date": "2022-04-12",
        "laboratory": "Lab. Behring",
        "doctor": "Dra. Maria Silvia M. Serzedo",
        "pdf": "silvana-source-pdfs/12_04_2022.pdf",
        "title_en": "Comprehensive panel — Dra. Serzedo (12 Apr 2022)",
        "title_pt": "Painel completo — Dra. Serzedo (12 abr 2022)"
      },
      {
        "date": "2019-06-13",
        "laboratory": "Lab. ICD · Ribeirão Preto",
        "doctor": "Dra. Daniela Souza Alvarenga",
        "pdf": "silvana-source-pdfs/resultado658832.pdf",
        "title_en": "Comprehensive panel — Dra. Alvarenga (13 Jun 2019)",
        "title_pt": "Painel completo — Dra. Alvarenga (13 jun 2019)"
      }
    ],
    "studies": [
      {
        "date": "2026-02-09",
        "category": "imaging",
        "modality_en": "Thyroid ultrasound",
        "modality_pt": "Ultrassom de tireoide",
        "title_en": "Cervical / thyroid ultrasound",
        "title_pt": "Ultrassonografia cervical / tireoide",
        "laboratory": "Instituto de Radiologia",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dr. José Álvaro Gonçalves Junior · Dr. Oswaldo Tonini",
        "conclusion_en": "Two left-lobe thyroid nodules: inferior pole 7.9 × 7.2 × 3.8 mm (TIRADS 4, stable) and superior third 9.1 × 7.8 × 7.2 mm (TIRADS 3). No suspicious lymphadenopathy or masses. Compared with 30 Mar 2023.",
        "conclusion_pt": "Dois nódulos no lobo esquerdo da tireoide: polo inferior 7,9 × 7,2 × 3,8 mm (TIRADS 4, estável) e terço superior 9,1 × 7,8 × 7,2 mm (TIRADS 3). Sem linfonodomegalias ou massas suspeitas. Comparado a 30 mar 2023.",
        "images": [
          "silvana-source-pdfs/silvana-thyroid-us-2026-02-09.jpeg"
        ]
      },
      {
        "date": "2026-02-09",
        "category": "imaging",
        "modality_en": "Sinus CT",
        "modality_pt": "TC dos seios da face",
        "title_en": "CT of the paranasal sinuses",
        "title_pt": "Tomografia dos seios da face",
        "laboratory": "Instituto de Radiologia",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dr. José Álvaro Gonçalves Junior · Dra. Danyela O. Gonçalves Prado",
        "conclusion_en": "Nasal septum deviated to the left with a large bony spur (0.6 cm). Paranasal sinuses normally aerated, no opacification; ostiomeatal complexes free. Indication: nasal obstruction.",
        "conclusion_pt": "Desvio do septo nasal para a esquerda, com grande esporão ósseo (0,6 cm). Seios da face com aeração normal, sem velamentos; complexos óstio-meatais livres. Indicação: obstrução nasal.",
        "images": [
          "silvana-source-pdfs/silvana-sinus-ct-2026-02-09.jpeg"
        ]
      },
      {
        "date": "2025-05-21",
        "category": "imaging",
        "modality_en": "Mammography",
        "modality_pt": "Mamografia",
        "title_en": "Bilateral digital mammography",
        "title_pt": "Mamografia digital bilateral",
        "laboratory": "Instituto de Radiologia",
        "requested_by": "Dra. Elisabete Pinheiro Ferreira Pires",
        "doctor": "Dr. José Álvaro Gonçalves Neto · Dr. José Álvaro Gonçalves Junior",
        "conclusion_en": "BI-RADS 2 (right and left). Fatty-replaced breasts with rare scattered punctiform calcifications; no grouped microcalcifications or other signs of malignancy. No significant change vs 16 Sep 2022.",
        "conclusion_pt": "BI-RADS 2 (direita e esquerda). Mamas lipossubstituídas com raras calcificações puntiformes esparsas; sem microcalcificações agrupadas ou sinais de malignidade. Sem alteração significativa vs 16 set 2022.",
        "images": [
          "silvana-source-pdfs/silvana-mammography-2025-05-21.jpeg"
        ]
      },
      {
        "date": "2025-04-14",
        "category": "pathology",
        "modality_en": "Cervical cytology",
        "modality_pt": "Citologia cervical",
        "title_en": "Cervical cytology (Pap smear)",
        "title_pt": "Citopatológico cervical (Papanicolaou)",
        "laboratory": "MM · Lab. de Patologia e Citologia",
        "requested_by": "Dra. Elisabete Pinheiro Ferreira Pires",
        "doctor": "Dra. Giovana Bachega Badiale Biagi · Dra. Margarida M. F. S. Moraes",
        "conclusion_en": "Benign cellular changes — inflammation and mild hypotrophy; inflammatory hypotrophic smear (Bethesda; Papanicolaou class II). No malignancy; microbiology absent.",
        "conclusion_pt": "Alterações celulares benignas — inflamação e hipotrofia leve; esfregaço hipotrófico inflamatório (Bethesda; classe II de Papanicolaou). Sem malignidade; microbiologia ausente.",
        "images": [
          "silvana-source-pdfs/silvana-cytology-2025-04-14.jpeg"
        ]
      },
      {
        "date": "2023-04-18",
        "category": "endoscopy",
        "modality_en": "Colonoscopy + biopsy",
        "modality_pt": "Colonoscopia + biópsia",
        "title_en": "Colonoscopy with polypectomy and biopsy",
        "title_pt": "Colonoscopia com polipectomia e biópsia",
        "laboratory": "ProctoGastro Clínica · biópsia: MM Lab.",
        "requested_by": "Dr. Fernando Luiz de Almeida Galante",
        "doctor": "Dr. Marley Ribeiro Feitosa",
        "conclusion_en": "2 mm sessile sigmoid polyp removed; biopsy = hyperplastic polyp, benign, no malignancy. Internal hemorrhoids; remaining colon and rectum normal. Repeat in 5 years.",
        "conclusion_pt": "Pólipo séssil de 2 mm no sigmoide removido; biópsia = pólipo hiperplásico, benigno, sem malignidade. Hemorroidas internas; demais cólon e reto normais. Repetir em 5 anos.",
        "images": [
          "silvana-source-pdfs/silvana-colonoscopy-2023-04-18.jpeg",
          "silvana-source-pdfs/silvana-colon-biopsy-2023-04-18.jpeg"
        ]
      },
      {
        "date": "2023-04-13",
        "category": "imaging",
        "modality_en": "Abdominal ultrasound",
        "modality_pt": "Ultrassom de abdome",
        "title_en": "Total abdomen ultrasound",
        "title_pt": "Ultrassonografia de abdome total",
        "laboratory": "Radiologia · Ribeirão Preto",
        "requested_by": "Dr. Fernando Luiz de Almeida Galante",
        "doctor": "Dra. Flávia Lemos de Oliveira",
        "conclusion_en": "Mild hepatic steatosis and a gallbladder polyp (3.6 mm on the anterior wall). Kidneys, spleen, pancreas and pelvic organs normal. No significant change vs 18 Nov 2020.",
        "conclusion_pt": "Esteatose hepática de discreta intensidade e pólipo vesicular (3,6 mm na parede anterior). Rins, baço, pâncreas e órgãos pélvicos normais. Sem alteração significativa vs 18 nov 2020.",
        "images": [
          "silvana-source-pdfs/silvana-abdominal-us-2023-04-13.jpeg"
        ]
      },
      {
        "date": "2023-03-30",
        "category": "imaging",
        "modality_en": "Thyroid ultrasound",
        "modality_pt": "Ultrassom de tireoide",
        "title_en": "Thyroid ultrasound with Doppler",
        "title_pt": "Ultrassonografia de tireoide com Doppler",
        "laboratory": "DMI · Diagnóstico Médico Integrado",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dr. Ricardo Issa",
        "conclusion_en": "Reduced-volume thyroid (4.28 cm³) with stable left-lobe nodules; reactional cervical lymph nodes. No significant change vs 18 Jan 2022.",
        "conclusion_pt": "Tireoide de volume reduzido (4,28 cm³) com nódulos estáveis no lobo esquerdo; linfonodos cervicais reacionais. Sem alteração significativa vs 18 jan 2022.",
        "images": [
          "silvana-source-pdfs/silvana-thyroid-us-2023-03-30.jpeg"
        ]
      },
      {
        "date": "2022-09-19",
        "category": "functional",
        "modality_en": "Urodynamic study",
        "modality_pt": "Estudo urodinâmico",
        "title_en": "Urodynamics (uroflowmetry, cystometry, pressure-flow)",
        "title_pt": "Urodinâmica (urofluxometria, cistometria, pressão-fluxo)",
        "laboratory": "Centro Avançado de Urologia · Ribeirão Preto",
        "requested_by": "Dr. Marcelo Baptistussi",
        "doctor": "Dra. Maria Teresa Pereira Cavalcante",
        "conclusion_en": "Normal free flow (Qmax 21 mL/s, minimal residue); voiding pressures suggest infravesical obstruction from vaginal dystopia. Impression: urethral instability, vaginal dystopia, vesical hyperactivity. Chief complaint: urinary urgency.",
        "conclusion_pt": "Fluxo livre normal (Qmáx 21 mL/s, resíduo mínimo); pressões miccionais sugerem obstrução infravesical por distopia vaginal. Parecer: instabilidade uretral, distopia vaginal, hiperatividade vesical. Queixa principal: urgência miccional.",
        "images": [
          "silvana-source-pdfs/silvana-urodynamics-2022-09-19-1.jpeg",
          "silvana-source-pdfs/silvana-urodynamics-2022-09-19-2.jpeg",
          "silvana-source-pdfs/silvana-urodynamics-2022-09-19-3.jpeg",
          "silvana-source-pdfs/silvana-urodynamics-2022-09-19-4.jpeg",
          "silvana-source-pdfs/silvana-urodynamics-2022-09-19-5.jpeg"
        ]
      },
      {
        "date": "2022-01-18",
        "category": "imaging",
        "modality_en": "Thyroid ultrasound",
        "modality_pt": "Ultrassom de tireoide",
        "title_en": "Thyroid ultrasound with Doppler",
        "title_pt": "Ultrassonografia de tireoide com Doppler",
        "laboratory": "DMI · Diagnóstico Médico Integrado",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dr. Ricardo Issa",
        "conclusion_en": "Reduced-volume thyroid (3.78 cm³) with stable left-lobe nodules; mildly enlarged right cervical lymph node — continue follow-up.",
        "conclusion_pt": "Tireoide de volume reduzido (3,78 cm³) com nódulos estáveis no lobo esquerdo; linfonodo cervical direito discretamente aumentado — manter seguimento.",
        "images": [
          "silvana-source-pdfs/silvana-thyroid-us-2022-01-18.jpeg"
        ]
      },
      {
        "date": "2022-01-18",
        "category": "imaging",
        "modality_en": "Sinus CT",
        "modality_pt": "TC dos seios da face",
        "title_en": "CT of the paranasal sinuses",
        "title_pt": "Tomografia dos seios da face",
        "laboratory": "CEDIRP",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dra. Fabiana de Deus Vieira",
        "conclusion_en": "Retention cyst / polyp in the left maxillary sinus (4 mm) and leftward nasal septal deviation. Indication: sinusopathy.",
        "conclusion_pt": "Cisto de retenção / pólipo no seio maxilar esquerdo (4 mm) e desvio do septo nasal para a esquerda. Indicação: sinusopatia.",
        "images": [
          "silvana-source-pdfs/silvana-sinus-ct-2022-01-18.jpeg"
        ]
      },
      {
        "date": "2021-07-13",
        "category": "imaging",
        "modality_en": "Thyroid ultrasound",
        "modality_pt": "Ultrassom de tireoide",
        "title_en": "Thyroid ultrasound with Doppler",
        "title_pt": "Ultrassonografia de tireoide com Doppler",
        "laboratory": "DMI · Diagnóstico Médico Integrado",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dr. Ricardo Issa",
        "conclusion_en": "Thyroid 4.06 cm³ with left-lobe nodules (superior nodule now with more cystic content); reactional right cervical lymph node.",
        "conclusion_pt": "Tireoide de 4,06 cm³ com nódulos no lobo esquerdo (nódulo superior agora com conteúdo mais cístico); linfonodo cervical direito reacional.",
        "images": [
          "silvana-source-pdfs/silvana-thyroid-us-2021-07-13.jpeg"
        ]
      },
      {
        "date": "2020-06-18",
        "category": "imaging",
        "modality_en": "Thyroid ultrasound",
        "modality_pt": "Ultrassom de tireoide",
        "title_en": "Thyroid ultrasound with Doppler",
        "title_pt": "Ultrassonografia de tireoide com Doppler",
        "laboratory": "DMI · Diagnóstico Médico Integrado",
        "requested_by": "Dr. José Roberto Chodraui",
        "doctor": "Dr. Ricardo Issa",
        "conclusion_en": "Left-lobe nodule and cyst; total thyroid volume 4.29 cm³. Reactional right cervical lymph node.",
        "conclusion_pt": "Nódulo e cisto no lobo esquerdo; volume tireoidiano total 4,29 cm³. Linfonodo cervical direito reacional.",
        "images": [
          "silvana-source-pdfs/silvana-thyroid-us-2020-06-18.jpeg"
        ]
      },
      {
        "date": "2017-12-15",
        "category": "pathology",
        "modality_en": "Colon biopsy",
        "modality_pt": "Biópsia de cólon",
        "title_en": "Sigmoid colon biopsy (histopathology)",
        "title_pt": "Biópsia de cólon sigmoide (anatomopatológico)",
        "laboratory": "Dr. Prates · Lab. de Patologia Cirúrgica",
        "requested_by": "Dr. Marcelo de Mello Torquato",
        "doctor": "Dr. Dayr Kiomizu Kazava",
        "conclusion_en": "Tubular adenoma with mild dysplasia (low-grade intraepithelial neoplasia, WHO) in the sigmoid colon; lesion base without atypia.",
        "conclusion_pt": "Adenoma tubular com displasia leve (neoplasia intraepitelial de baixo grau, OMS) no cólon sigmoide; base da lesão sem atipias.",
        "images": [
          "silvana-source-pdfs/silvana-colon-biopsy-2017-12-15.jpeg"
        ]
      }
    ],
    "panels": [
      {
        "slug": "thyroid",
        "title_en": "Thyroid panel",
        "title_pt": "Painel tireoidiano",
        "subtitle_en": "TSH, T4 free, T3 free, anti-TPO",
        "subtitle_pt": "TSH, T4 livre, T3 livre, anti-TPO",
        "markers": [
          {
            "marker_en": "TSH (ultra-sensitive)",
            "marker_pt": "TSH ultra-sensível",
            "unit": "µIU/mL",
            "ref_low": 0.55,
            "ref_high": 4.78,
            "ref_text_en": "Adults: 0.55 – 4.78 µIU/mL",
            "ref_text_pt": "Adultos: 0,55 a 4,78 µIU/mL",
            "points": [
              {
                "date": "2026-03-27",
                "value": 2.767
              },
              {
                "date": "2026-02-18",
                "value": 4.755,
                "flag": "H",
                "note_en": "Briefly above adult range",
                "note_pt": "Brevemente acima do intervalo adulto"
              },
              {
                "date": "2025-10-24",
                "value": 2.902
              },
              {
                "date": "2026-04-25",
                "value": 2.974
              },
              {
                "date": "2024-02-27",
                "value": 2.91
              },
              {
                "date": "2023-02-16",
                "value": 3.8
              },
              {
                "date": "2022-04-12",
                "value": 2.433
              },
              {
                "date": "2021-07-13",
                "value": 3.14
              },
              {
                "date": "2019-06-13",
                "value": 3.16
              }
            ]
          },
          {
            "marker_en": "T4 Free",
            "marker_pt": "T4 livre",
            "unit": "ng/dL",
            "ref_low": 0.8,
            "ref_high": 2,
            "ref_text_en": "Euthyroid: 0.80 – 2.00 ng/dL",
            "ref_text_pt": "Eutiroidianos: 0,80 a 2,00 ng/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 1.26
              },
              {
                "date": "2026-02-18",
                "value": 1.15
              },
              {
                "date": "2025-10-24",
                "value": 1.19
              },
              {
                "date": "2024-02-27",
                "value": 1.04
              },
              {
                "date": "2023-02-16",
                "value": 1.18
              },
              {
                "date": "2022-04-12",
                "value": 1.27
              },
              {
                "date": "2021-07-13",
                "value": 1.24
              },
              {
                "date": "2019-06-13",
                "value": 1.35
              }
            ]
          },
          {
            "marker_en": "T3 Free",
            "marker_pt": "T3 livre",
            "unit": "pg/mL",
            "ref_low": 1.5,
            "ref_high": 5,
            "ref_text_en": "Euthyroid: 1.50 – 5.00 pg/mL",
            "ref_text_pt": "Eutiroidianos: 1,50 a 5,00 pg/mL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 3.1
              },
              {
                "date": "2024-02-27",
                "value": 3.2
              }
            ]
          },
          {
            "marker_en": "T3 Total",
            "marker_pt": "T3 total (triiodotironina)",
            "unit": "ng/dL",
            "ref_low": 80,
            "ref_high": 200,
            "ref_text_en": "80 – 200 ng/dL",
            "ref_text_pt": "80,0 a 200,0 ng/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 96.26
              }
            ]
          },
          {
            "marker_en": "Anti-TPO antibodies",
            "marker_pt": "Anti-tireoperoxidase",
            "unit": "UI/mL",
            "ref_low": null,
            "ref_high": 34,
            "ref_text_en": "Up to 34 UI/mL",
            "ref_text_pt": "Até 34 UI/mL",
            "points": [
              {
                "date": "2019-06-13",
                "value": 10.78
              }
            ]
          }
        ]
      },
      {
        "slug": "lipids",
        "title_en": "Lipid panel",
        "title_pt": "Lipidograma",
        "subtitle_en": "Total cholesterol, LDL, HDL, triglycerides",
        "subtitle_pt": "Colesterol total, LDL, HDL, triglicerídeos",
        "markers": [
          {
            "marker_en": "Total cholesterol",
            "marker_pt": "Colesterol total",
            "unit": "mg/dL",
            "ref_low": null,
            "ref_high": 190,
            "ref_text_en": "Desirable: < 190 mg/dL",
            "ref_text_pt": "Desejável: < 190 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 206,
                "flag": "H"
              },
              {
                "date": "2026-02-18",
                "value": 218,
                "flag": "H"
              },
              {
                "date": "2024-02-27",
                "value": 197.7,
                "flag": "H"
              },
              {
                "date": "2023-02-16",
                "value": 233,
                "flag": "H"
              },
              {
                "date": "2021-08-14",
                "value": 208,
                "flag": "H"
              },
              {
                "date": "2019-06-13",
                "value": 196,
                "flag": "H"
              }
            ]
          },
          {
            "marker_en": "LDL cholesterol",
            "marker_pt": "LDL",
            "unit": "mg/dL",
            "ref_low": null,
            "ref_high": 130,
            "ref_text_en": "Low cardiovascular risk: < 130 mg/dL",
            "ref_text_pt": "Risco cardiovascular baixo: < 130 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 128.6
              },
              {
                "date": "2026-02-18",
                "value": 127.1
              },
              {
                "date": "2024-02-27",
                "value": 119.9
              },
              {
                "date": "2023-02-16",
                "value": 140,
                "flag": "H"
              },
              {
                "date": "2019-06-13",
                "value": 122
              }
            ]
          },
          {
            "marker_en": "HDL cholesterol",
            "marker_pt": "HDL",
            "unit": "mg/dL",
            "ref_low": 40,
            "ref_high": null,
            "ref_text_en": "Desirable: > 40 mg/dL",
            "ref_text_pt": "Desejável: > 40 mg/dL",
            "points": [
              {
                "date": "2026-02-18",
                "value": 49
              },
              {
                "date": "2024-02-27",
                "value": 50
              },
              {
                "date": "2023-02-16",
                "value": 46
              },
              {
                "date": "2021-08-14",
                "value": 39,
                "flag": "L"
              },
              {
                "date": "2019-06-13",
                "value": 42
              }
            ]
          },
          {
            "marker_en": "Triglycerides",
            "marker_pt": "Triglicérides",
            "unit": "mg/dL",
            "ref_low": null,
            "ref_high": 150,
            "ref_text_en": "Desirable (fasting): < 150 mg/dL",
            "ref_text_pt": "Desejável (jejum): < 150 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 174,
                "flag": "H"
              },
              {
                "date": "2026-02-18",
                "value": 210,
                "flag": "H"
              },
              {
                "date": "2024-02-27",
                "value": 161.2,
                "flag": "H"
              },
              {
                "date": "2023-02-16",
                "value": 233,
                "flag": "H"
              },
              {
                "date": "2021-08-14",
                "value": 222,
                "flag": "H"
              },
              {
                "date": "2019-06-13",
                "value": 158,
                "flag": "H"
              }
            ]
          },
          {
            "marker_en": "Non-HDL cholesterol",
            "marker_pt": "Não-HDL",
            "unit": "mg/dL",
            "ref_low": null,
            "ref_high": 160,
            "ref_text_en": "Low cardiovascular risk: < 160 mg/dL",
            "ref_text_pt": "Risco cardiovascular baixo: < 160 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 163.4,
                "flag": "H"
              },
              {
                "date": "2026-02-18",
                "value": 169.1,
                "flag": "H"
              },
              {
                "date": "2024-02-27",
                "value": 147.7
              },
              {
                "date": "2023-02-16",
                "value": 187,
                "flag": "H"
              }
            ]
          },
          {
            "marker_en": "VLDL cholesterol",
            "marker_pt": "VLDL",
            "unit": "mg/dL",
            "ref_low": null,
            "ref_high": 30,
            "ref_text_en": "Desirable: < 30 mg/dL",
            "ref_text_pt": "Desejável: < 30 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 34.8,
                "flag": "H"
              },
              {
                "date": "2026-02-18",
                "value": 42,
                "flag": "H"
              },
              {
                "date": "2024-02-27",
                "value": 27.8
              }
            ]
          }
        ]
      },
      {
        "slug": "glucose",
        "title_en": "Glucose & metabolic",
        "title_pt": "Glicose & metabólico",
        "subtitle_en": "Fasting glucose, HbA1c, insulin, HOMA-IR",
        "subtitle_pt": "Glicemia em jejum, HbA1c, insulina, HOMA-IR",
        "markers": [
          {
            "marker_en": "Fasting glucose",
            "marker_pt": "Glicemia em jejum",
            "unit": "mg/dL",
            "ref_low": 70,
            "ref_high": 99,
            "ref_text_en": "Normal: 70 – 99 mg/dL",
            "ref_text_pt": "Normal: 70 a 99 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 75
              },
              {
                "date": "2026-02-18",
                "value": 72
              },
              {
                "date": "2024-07-24",
                "value": 86
              },
              {
                "date": "2024-02-27",
                "value": 79.5
              },
              {
                "date": "2023-02-16",
                "value": 89
              },
              {
                "date": "2022-04-12",
                "value": 80.9
              },
              {
                "date": "2021-08-14",
                "value": 92
              },
              {
                "date": "2019-12-06",
                "value": 87
              },
              {
                "date": "2019-06-13",
                "value": 87
              }
            ]
          },
          {
            "marker_en": "HbA1c (glycated)",
            "marker_pt": "Hemoglobina glicada (HbA1c)",
            "unit": "%",
            "ref_low": null,
            "ref_high": 5.7,
            "ref_text_en": "Normal: < 5.7%   |   Prediabetes: 5.7 – 6.4%",
            "ref_text_pt": "Normal: < 5,7%   |   Pré-diabetes: 5,7 a 6,4%",
            "points": [
              {
                "date": "2026-04-25",
                "value": 5.1
              },
              {
                "date": "2023-02-16",
                "value": 5.2
              },
              {
                "date": "2019-06-13",
                "value": 5.5
              }
            ]
          },
          {
            "marker_en": "Insulin (fasting)",
            "marker_pt": "Insulina (jejum)",
            "unit": "µIU/mL",
            "ref_low": null,
            "ref_high": 30,
            "ref_text_en": "After 12 h fasting: up to 30 µIU/mL",
            "ref_text_pt": "Após 12 h de jejum: até 30 µIU/mL",
            "points": [
              {
                "date": "2022-04-12",
                "value": 5.24
              },
              {
                "date": "2019-06-13",
                "value": 7.89
              }
            ]
          },
          {
            "marker_en": "HOMA-IR",
            "marker_pt": "HOMA-IR",
            "unit": "",
            "ref_low": null,
            "ref_high": 3.4,
            "ref_text_en": "> 3.40 suggests insulin resistance",
            "ref_text_pt": "> 3,40 sugere resistência à insulina",
            "points": [
              {
                "date": "2022-04-12",
                "value": 1.05
              }
            ]
          }
        ]
      },
      {
        "slug": "kidney",
        "title_en": "Kidney function",
        "title_pt": "Função renal",
        "subtitle_en": "Creatinine, eGFR, urea",
        "subtitle_pt": "Creatinina, TFG estimada, ureia",
        "markers": [
          {
            "marker_en": "Creatinine",
            "marker_pt": "Creatinina",
            "unit": "mg/dL",
            "ref_low": 0.6,
            "ref_high": 1.4,
            "ref_text_en": "Adults > 15 y: 0.60 – 1.40 mg/dL",
            "ref_text_pt": "Acima de 15 anos: 0,60 a 1,40 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 1
              },
              {
                "date": "2026-02-18",
                "value": 1.1
              },
              {
                "date": "2024-07-24",
                "value": 0.8
              },
              {
                "date": "2023-02-16",
                "value": 0.88
              },
              {
                "date": "2021-08-14",
                "value": 0.8
              }
            ]
          },
          {
            "marker_en": "Estimated GFR (MDRD)",
            "marker_pt": "Taxa de filtração glomerular (eTFG, MDRD)",
            "unit": "mL/min/1.73m²",
            "ref_low": 60,
            "ref_high": null,
            "ref_text_en": "Adults: > 60 mL/min/1.73 m²",
            "ref_text_pt": "Adultos: maior que 60 mL/min/1,73 m²",
            "points": [
              {
                "date": "2026-02-18",
                "value": 58.2,
                "flag": "L",
                "note_en": "Briefly below the > 60 threshold; back > 60 in April",
                "note_pt": "Brevemente abaixo do limite > 60; retornou > 60 em abril"
              },
              {
                "date": "2024-07-24",
                "value": 60,
                "value_text": "> 60"
              },
              {
                "date": "2023-02-16",
                "value": 89.78
              }
            ]
          },
          {
            "marker_en": "Urea",
            "marker_pt": "Ureia",
            "unit": "mg/dL",
            "ref_low": 9,
            "ref_high": 50,
            "ref_text_en": "9 – 50 mg/dL",
            "ref_text_pt": "9 a 50 mg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 26
              },
              {
                "date": "2026-02-18",
                "value": 27
              },
              {
                "date": "2023-02-16",
                "value": 28
              },
              {
                "date": "2021-08-14",
                "value": 28
              }
            ]
          }
        ]
      },
      {
        "slug": "liver",
        "title_en": "Liver function",
        "title_pt": "Função hepática",
        "subtitle_en": "AST (TGO), ALT (TGP), GGT",
        "subtitle_pt": "TGO/AST, TGP/ALT, GGT",
        "markers": [
          {
            "marker_en": "AST (TGO)",
            "marker_pt": "TGO (AST)",
            "unit": "U/L",
            "ref_low": null,
            "ref_high": 32,
            "ref_text_en": "Women: up to 32 U/L",
            "ref_text_pt": "Mulheres: até 32 U/L",
            "points": [
              {
                "date": "2026-04-25",
                "value": 31
              },
              {
                "date": "2026-04-13",
                "value": 20
              },
              {
                "date": "2023-02-16",
                "value": 21
              },
              {
                "date": "2021-08-14",
                "value": 23
              }
            ]
          },
          {
            "marker_en": "ALT (TGP)",
            "marker_pt": "TGP (ALT)",
            "unit": "U/L",
            "ref_low": null,
            "ref_high": 33,
            "ref_text_en": "Women: up to 33 U/L",
            "ref_text_pt": "Mulheres: até 33 U/L",
            "points": [
              {
                "date": "2026-04-25",
                "value": 25
              },
              {
                "date": "2026-04-13",
                "value": 28
              },
              {
                "date": "2023-02-16",
                "value": 24
              },
              {
                "date": "2021-08-14",
                "value": 28
              },
              {
                "date": "2019-12-06",
                "value": 19
              }
            ]
          },
          {
            "marker_en": "GGT",
            "marker_pt": "Gama-GT",
            "unit": "U/L",
            "ref_low": null,
            "ref_high": 40,
            "ref_text_en": "Women: < 40 U/L",
            "ref_text_pt": "Mulheres: < 40 U/L",
            "points": [
              {
                "date": "2026-04-25",
                "value": 18
              },
              {
                "date": "2026-02-18",
                "value": 14
              },
              {
                "date": "2023-02-16",
                "value": 16
              },
              {
                "date": "2021-07-13",
                "value": 17
              },
              {
                "date": "2019-12-06",
                "value": 13
              }
            ]
          }
        ]
      },
      {
        "slug": "vitamins-minerals",
        "title_en": "Vitamins & minerals",
        "title_pt": "Vitaminas & minerais",
        "subtitle_en": "Vitamin D, B12, iron, ferritin, electrolytes",
        "subtitle_pt": "Vitamina D, B12, ferro, ferritina, eletrólitos",
        "markers": [
          {
            "marker_en": "Vitamin D (25-OH)",
            "marker_pt": "Vitamina D (25-hidroxi)",
            "unit": "ng/mL",
            "ref_low": 30,
            "ref_high": 60,
            "ref_text_en": "Risk groups: 30 – 60 ng/mL   |   General: > 20 ng/mL",
            "ref_text_pt": "Grupos de risco: 30 a 60 ng/mL   |   Geral: > 20 ng/mL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 61.49,
                "flag": "H",
                "note_en": "Just above the upper risk-group bound",
                "note_pt": "Logo acima do limite superior do grupo de risco"
              },
              {
                "date": "2026-02-18",
                "value": 42.1
              },
              {
                "date": "2025-12-12",
                "value": 36.8
              },
              {
                "date": "2019-06-13",
                "value": 35.1
              }
            ]
          },
          {
            "marker_en": "Vitamin B12",
            "marker_pt": "Vitamina B12",
            "unit": "pg/mL",
            "ref_low": 211,
            "ref_high": 911,
            "ref_text_en": "211 – 911 pg/mL",
            "ref_text_pt": "211 a 911 pg/mL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 557
              },
              {
                "date": "2022-04-12",
                "value": 388
              },
              {
                "date": "2019-06-13",
                "value": 431
              }
            ]
          },
          {
            "marker_en": "Iron (serum)",
            "marker_pt": "Ferro sérico",
            "unit": "µg/dL",
            "ref_low": 50,
            "ref_high": 170,
            "ref_text_en": "Women: 50 – 170 µg/dL",
            "ref_text_pt": "Mulheres: 50 a 170 µg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 105
              }
            ]
          },
          {
            "marker_en": "Ferritin",
            "marker_pt": "Ferritina",
            "unit": "ng/mL",
            "ref_low": 10,
            "ref_high": 280,
            "ref_text_en": "Post-menopausal women: 10 – 280 ng/mL",
            "ref_text_pt": "Mulheres pós-menopausa: 10 a 280 ng/mL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 214
              },
              {
                "date": "2022-04-12",
                "value": 177.5
              },
              {
                "date": "2019-06-13",
                "value": 206
              }
            ]
          },
          {
            "marker_en": "Magnesium",
            "marker_pt": "Magnésio",
            "unit": "mg/dL",
            "ref_low": 1.6,
            "ref_high": 2.6,
            "ref_text_en": "1.6 – 2.6 mg/dL",
            "ref_text_pt": "1,6 a 2,6 mg/dL",
            "points": [
              {
                "date": "2023-02-16",
                "value": 2.23
              },
              {
                "date": "2022-04-12",
                "value": 2.4
              },
              {
                "date": "2019-06-13",
                "value": 1.83
              }
            ]
          },
          {
            "marker_en": "Calcium (total)",
            "marker_pt": "Cálcio total",
            "unit": "mg/dL",
            "ref_low": 8.3,
            "ref_high": 10.6,
            "ref_text_en": "8.3 – 10.6 mg/dL",
            "ref_text_pt": "8,3 a 10,6 mg/dL",
            "points": [
              {
                "date": "2026-02-18",
                "value": 9.1
              },
              {
                "date": "2023-02-16",
                "value": 10.1
              },
              {
                "date": "2019-06-13",
                "value": 9.1
              }
            ]
          },
          {
            "marker_en": "Zinc",
            "marker_pt": "Zinco",
            "unit": "µg/dL",
            "ref_low": 70,
            "ref_high": 120,
            "ref_text_en": "70 – 120 µg/dL",
            "ref_text_pt": "70 a 120 µg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 81.5
              },
              {
                "date": "2019-06-13",
                "value": 97.9
              }
            ]
          },
          {
            "marker_en": "Sodium",
            "marker_pt": "Sódio",
            "unit": "mmol/L",
            "ref_low": 136,
            "ref_high": 145,
            "ref_text_en": "136 – 145 mmol/L",
            "ref_text_pt": "136 a 145 mmol/L",
            "points": [
              {
                "date": "2026-04-25",
                "value": 142.5
              },
              {
                "date": "2023-02-16",
                "value": 140
              },
              {
                "date": "2019-06-13",
                "value": 142
              }
            ]
          },
          {
            "marker_en": "Potassium",
            "marker_pt": "Potássio",
            "unit": "mmol/L",
            "ref_low": 3.5,
            "ref_high": 5.1,
            "ref_text_en": "3.5 – 5.1 mmol/L",
            "ref_text_pt": "3,5 a 5,1 mmol/L",
            "points": [
              {
                "date": "2026-04-25",
                "value": 4.7
              },
              {
                "date": "2023-02-16",
                "value": 4.7
              },
              {
                "date": "2019-06-13",
                "value": 4.4
              }
            ]
          },
          {
            "marker_en": "Phosphorus",
            "marker_pt": "Fósforo",
            "unit": "mg/dL",
            "ref_low": 2.5,
            "ref_high": 4.5,
            "ref_text_en": "Adults: 2.5 – 4.5 mg/dL",
            "ref_text_pt": "Adultos: 2,5 a 4,5 mg/dL",
            "points": [
              {
                "date": "2019-06-13",
                "value": 4.5
              }
            ]
          },
          {
            "marker_en": "Uric acid",
            "marker_pt": "Ácido úrico",
            "unit": "mg/dL",
            "ref_low": 2.4,
            "ref_high": 5.7,
            "ref_text_en": "Women: 2.4 – 5.7 mg/dL",
            "ref_text_pt": "Mulheres: 2,4 a 5,7 mg/dL",
            "points": [
              {
                "date": "2025-01-22",
                "value": 5.1
              },
              {
                "date": "2023-02-16",
                "value": 5.1
              },
              {
                "date": "2019-06-13",
                "value": 4.6
              }
            ]
          }
        ]
      },
      {
        "slug": "hormones",
        "title_en": "Hormones",
        "title_pt": "Hormônios",
        "subtitle_en": "Cortisol, FSH, sex steroids",
        "subtitle_pt": "Cortisol, FSH, esteroides sexuais",
        "markers": [
          {
            "marker_en": "Cortisol (8–9 AM basal)",
            "marker_pt": "Cortisol basal (8–9 h)",
            "unit": "µg/dL",
            "ref_low": 7,
            "ref_high": 21,
            "ref_text_en": "Basal 8–9 AM: 7.0 – 21.0 µg/dL",
            "ref_text_pt": "Basal 8–9 h: 7,0 a 21,0 µg/dL",
            "points": [
              {
                "date": "2026-04-25",
                "value": 8.11
              },
              {
                "date": "2024-02-27",
                "value": 5.93,
                "flag": "L",
                "note_en": "Below the morning reference window",
                "note_pt": "Abaixo do intervalo de referência matinal"
              },
              {
                "date": "2022-04-12",
                "value": 9.48
              }
            ]
          },
          {
            "marker_en": "FSH",
            "marker_pt": "FSH",
            "unit": "mIU/mL",
            "ref_low": 23,
            "ref_high": 116.3,
            "ref_text_en": "Post-menopause: 23.0 – 116.3 mIU/mL",
            "ref_text_pt": "Pós-menopausa: 23,0 a 116,3 mIU/mL",
            "points": [
              {
                "date": "2024-02-27",
                "value": 91.46
              },
              {
                "date": "2019-06-13",
                "value": 65.41
              }
            ]
          },
          {
            "marker_en": "Estradiol",
            "marker_pt": "Estradiol",
            "unit": "pg/mL",
            "ref_low": null,
            "ref_high": 28,
            "ref_text_en": "Post-menopause: ≤ 28 pg/mL",
            "ref_text_pt": "Pós-menopausa: ≤ 28 pg/mL",
            "points": [
              {
                "date": "2026-04-13",
                "value": 13
              },
              {
                "date": "2019-06-13",
                "value": 32.99,
                "flag": "H"
              }
            ]
          },
          {
            "marker_en": "Progesterone",
            "marker_pt": "Progesterona",
            "unit": "ng/mL",
            "ref_low": null,
            "ref_high": null,
            "ref_text_en": "Post-menopause: typically < 0.5 ng/mL",
            "ref_text_pt": "Pós-menopausa: tipicamente < 0,5 ng/mL",
            "points": [
              {
                "date": "2019-06-13",
                "value": 0.237
              }
            ]
          },
          {
            "marker_en": "Total testosterone",
            "marker_pt": "Testosterona total",
            "unit": "ng/dL",
            "ref_low": 13,
            "ref_high": 53,
            "ref_text_en": "Women: 13 – 53 ng/dL",
            "ref_text_pt": "Mulheres: 13 a 53 ng/dL",
            "points": [
              {
                "date": "2026-04-13",
                "value": 24
              },
              {
                "date": "2019-06-13",
                "value": 27.1
              }
            ]
          },
          {
            "marker_en": "Free testosterone (calc)",
            "marker_pt": "Testosterona livre calculada",
            "unit": "ng/dL",
            "ref_low": 0.1,
            "ref_high": 1.41,
            "ref_text_en": "Women post-menopause: 0.10 – 1.41 ng/dL",
            "ref_text_pt": "Mulheres pós-menopausa: 0,10 a 1,41 ng/dL",
            "points": [
              {
                "date": "2026-04-13",
                "value": 0.39
              }
            ]
          },
          {
            "marker_en": "SHBG",
            "marker_pt": "SHBG",
            "unit": "nmol/L",
            "ref_low": 11.7,
            "ref_high": 155.2,
            "ref_text_en": "Women: 11.7 – 155.2 nmol/L",
            "ref_text_pt": "Mulheres: 11,7 a 155,2 nmol/L",
            "points": [
              {
                "date": "2026-04-13",
                "value": 39.4
              }
            ]
          }
        ]
      },
      {
        "slug": "inflammation-autoimmune",
        "title_en": "Inflammation & autoimmune",
        "title_pt": "Inflamação & autoimunidade",
        "subtitle_en": "ESR, rheumatoid factor, complement, ANA, anti-CCP, ANCA",
        "subtitle_pt": "VHS, fator reumatoide, complemento, FAN, anti-CCP, ANCA",
        "markers": [
          {
            "marker_en": "ESR (1st hour)",
            "marker_pt": "VHS (1ª hora)",
            "unit": "mm/h",
            "ref_low": null,
            "ref_high": 25,
            "ref_text_en": "Women: up to ~25 mm/h",
            "ref_text_pt": "Mulheres: até ~25 mm/h",
            "points": [
              {
                "date": "2019-06-13",
                "value": 30,
                "flag": "H"
              }
            ]
          },
          {
            "marker_en": "Rheumatoid factor",
            "marker_pt": "Fator reumatoide (FR)",
            "unit": "IU/mL",
            "ref_low": null,
            "ref_high": 20,
            "ref_text_en": "Negative: < 20 IU/mL",
            "ref_text_pt": "Pacientes normais: até 20 IU/mL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 2.5
              },
              {
                "date": "2022-04-12",
                "value": 12
              }
            ]
          },
          {
            "marker_en": "Complement C3",
            "marker_pt": "Complemento C3",
            "unit": "mg/dL",
            "ref_low": 75,
            "ref_high": 135,
            "ref_text_en": "75 – 135 mg/dL",
            "ref_text_pt": "75 a 135 mg/dL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 162.6,
                "flag": "H",
                "note_en": "Elevated — acute-phase reactant",
                "note_pt": "Elevado — reagente de fase aguda"
              }
            ]
          },
          {
            "marker_en": "Complement C4",
            "marker_pt": "Complemento C4",
            "unit": "mg/dL",
            "ref_low": 19,
            "ref_high": 52,
            "ref_text_en": "19 – 52 mg/dL",
            "ref_text_pt": "19 a 52 mg/dL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 28.1
              }
            ]
          },
          {
            "marker_en": "CH50 (total complement)",
            "marker_pt": "CH50 (complemento total)",
            "unit": "U/mL",
            "ref_low": 42,
            "ref_high": 95,
            "ref_text_en": "42.0 – 95.0 U/mL",
            "ref_text_pt": "42,0 a 95,0 U/mL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 46.59
              }
            ]
          },
          {
            "marker_en": "ANA (HEp-2)",
            "marker_pt": "FAN (HEp-2)",
            "unit": "",
            "ref_low": null,
            "ref_high": null,
            "ref_text_en": "Non-reactive",
            "ref_text_pt": "Não reagente",
            "points": [
              {
                "date": "2025-10-24",
                "value": null,
                "value_text": "Non-reactive"
              },
              {
                "date": "2022-04-12",
                "value": null,
                "value_text": "Non-reactive"
              }
            ]
          },
          {
            "marker_en": "Anti-CCP",
            "marker_pt": "Anti-CCP",
            "unit": "U/mL",
            "ref_low": null,
            "ref_high": 7,
            "ref_text_en": "Negative: < 7.0 U/mL",
            "ref_text_pt": "Negativo: < 7,0 U/mL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 0.7
              }
            ]
          },
          {
            "marker_en": "Anti-SSA (Ro)",
            "marker_pt": "Anti-SSA (Ro)",
            "unit": "U/mL",
            "ref_low": null,
            "ref_high": 7,
            "ref_text_en": "Non-reactive: < 7.0 U/mL",
            "ref_text_pt": "Não reagente: < 7,0 U/mL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "Anti-SSB (La)",
            "marker_pt": "Anti-SSB (La)",
            "unit": "U/mL",
            "ref_low": null,
            "ref_high": 7,
            "ref_text_en": "Non-reactive: < 7.0 U/mL",
            "ref_text_pt": "Não reagente: < 7,0 U/mL",
            "points": [
              {
                "date": "2025-10-24",
                "value": 0.3,
                "value_text": "< 0.3"
              }
            ]
          },
          {
            "marker_en": "ANCA (p/c)",
            "marker_pt": "ANCA (p/c)",
            "unit": "",
            "ref_low": null,
            "ref_high": null,
            "ref_text_en": "Non-reactive",
            "ref_text_pt": "Não reagente",
            "points": [
              {
                "date": "2025-10-24",
                "value": null,
                "value_text": "Non-reactive"
              }
            ]
          }
        ]
      },
      {
        "slug": "allergy",
        "title_en": "Allergy",
        "title_pt": "Alergia",
        "subtitle_en": "Total IgE and specific IgE panel — Dec 2025",
        "subtitle_pt": "IgE total e painel de IgE específicos — dez 2025",
        "markers": [
          {
            "marker_en": "IgE total",
            "marker_pt": "Imunoglobulina E total",
            "unit": "UI/mL",
            "ref_low": 1,
            "ref_high": 183,
            "ref_text_en": "1.0 – 183.0 UI/mL",
            "ref_text_pt": "1,0 a 183,0 UI/mL",
            "points": [
              {
                "date": "2025-12-12",
                "value": 21
              }
            ]
          },
          {
            "marker_en": "IgE — tree pollens (TX7)",
            "marker_pt": "IgE — pólens de árvores (TX7)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Undetectable: < 0.10 kU/L",
            "ref_text_pt": "Indetectável: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.10"
              }
            ]
          },
          {
            "marker_en": "IgE — fungi (MX1)",
            "marker_pt": "IgE — fungos (MX1)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — grasses (GX2)",
            "marker_pt": "IgE — gramíneas (GX2)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — feathers (EX71)",
            "marker_pt": "IgE — penas (EX71)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — cockroach (I6)",
            "marker_pt": "IgE — barata (I6)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — D. farinae (D2)",
            "marker_pt": "IgE — D. farinae (D2)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — D. pteronyssinus (D1)",
            "marker_pt": "IgE — D. pteronyssinus (D1)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — Blomia tropicalis (D201)",
            "marker_pt": "IgE — Blomia tropicalis (D201)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — dog dander (E5)",
            "marker_pt": "IgE — caspa de cão (E5)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          },
          {
            "marker_en": "IgE — cat epithelium (E1)",
            "marker_pt": "IgE — epitélio de gato (E1)",
            "unit": "kU/L",
            "ref_low": null,
            "ref_high": 0.1,
            "ref_text_en": "Below detection: < 0.10 kU/L",
            "ref_text_pt": "Abaixo da detecção: < 0,10 kU/L",
            "points": [
              {
                "date": "2025-12-12",
                "value": 0.1,
                "value_text": "< 0.1"
              }
            ]
          }
        ]
      },
      {
        "slug": "hematology",
        "title_en": "Hematology — CBC",
        "title_pt": "Hematologia — Hemograma",
        "subtitle_en": "Red & white cells, platelets",
        "subtitle_pt": "Hemácias, leucócitos e plaquetas",
        "markers": [
          {
            "marker_en": "Hemoglobin",
            "marker_pt": "Hemoglobina",
            "unit": "g/dL",
            "ref_low": 11.7,
            "ref_high": 15.7,
            "ref_text_en": "Women: 11.7 – 15.7 g/dL",
            "ref_text_pt": "Mulheres: 11,7 a 15,7 g/dL",
            "points": [
              {
                "date": "2025-12-12",
                "value": 15.73,
                "flag": "H",
                "note_en": "Just over the upper bound; repeat reading confirmed",
                "note_pt": "Logo acima do limite; resultado confirmado em nova leitura"
              },
              {
                "date": "2026-02-18",
                "value": 14.92
              },
              {
                "date": "2025-10-24",
                "value": 14.4
              },
              {
                "date": "2024-07-24",
                "value": 14.8
              },
              {
                "date": "2024-02-27",
                "value": 14.63
              },
              {
                "date": "2023-02-16",
                "value": 15
              },
              {
                "date": "2019-06-13",
                "value": 15.9
              }
            ]
          },
          {
            "marker_en": "Red blood cells",
            "marker_pt": "Eritrócitos",
            "unit": "million/mm³",
            "ref_low": 3.7,
            "ref_high": 5.3,
            "ref_text_en": "Women: 3.70 – 5.30 million/mm³",
            "ref_text_pt": "Mulheres: 3,70 a 5,30 milhões/mm³",
            "points": [
              {
                "date": "2025-12-12",
                "value": 5.45,
                "flag": "H"
              },
              {
                "date": "2026-02-18",
                "value": 5.08
              },
              {
                "date": "2025-10-24",
                "value": 4.99
              },
              {
                "date": "2024-07-24",
                "value": 5.28
              },
              {
                "date": "2024-02-27",
                "value": 4.93
              },
              {
                "date": "2023-02-16",
                "value": 5.22
              },
              {
                "date": "2019-06-13",
                "value": 5.49,
                "flag": "H"
              }
            ]
          },
          {
            "marker_en": "Hematocrit",
            "marker_pt": "Hematócrito",
            "unit": "%",
            "ref_low": 35,
            "ref_high": 47,
            "ref_text_en": "Women: 35.0 – 47.0 %",
            "ref_text_pt": "Mulheres: 35,0 a 47,0 %",
            "points": [
              {
                "date": "2025-12-12",
                "value": 47.5,
                "flag": "H"
              },
              {
                "date": "2026-02-18",
                "value": 45.1
              },
              {
                "date": "2025-10-24",
                "value": 43.25
              },
              {
                "date": "2024-07-24",
                "value": 45
              }
            ]
          },
          {
            "marker_en": "Leukocytes (WBC)",
            "marker_pt": "Leucócitos",
            "unit": "/mm³",
            "ref_low": 3600,
            "ref_high": 11000,
            "ref_text_en": "3,600 – 11,000 /mm³",
            "ref_text_pt": "3.600 a 11.000 /mm³",
            "points": [
              {
                "date": "2025-12-12",
                "value": 9180
              },
              {
                "date": "2026-02-18",
                "value": 8750
              },
              {
                "date": "2025-10-24",
                "value": 8030
              },
              {
                "date": "2024-07-24",
                "value": 7230
              },
              {
                "date": "2024-02-27",
                "value": 8600
              },
              {
                "date": "2023-02-16",
                "value": 6280
              },
              {
                "date": "2019-06-13",
                "value": 8000
              }
            ]
          },
          {
            "marker_en": "Platelets",
            "marker_pt": "Plaquetas",
            "unit": "/mm³",
            "ref_low": 140000,
            "ref_high": 400000,
            "ref_text_en": "140,000 – 400,000 /mm³",
            "ref_text_pt": "140.000 a 400.000 /mm³",
            "points": [
              {
                "date": "2025-12-12",
                "value": 426400,
                "flag": "H",
                "note_en": "Mild reactive thrombocytosis — value confirmed on the same sample",
                "note_pt": "Trombocitose reativa discreta — valor confirmado na mesma amostra"
              },
              {
                "date": "2026-02-18",
                "value": 361100
              },
              {
                "date": "2025-10-24",
                "value": 314000
              },
              {
                "date": "2024-07-24",
                "value": 321000
              },
              {
                "date": "2024-02-27",
                "value": 359000
              },
              {
                "date": "2023-02-16",
                "value": 327000
              },
              {
                "date": "2019-06-13",
                "value": 365000
              }
            ]
          }
        ]
      },
      {
        "slug": "other",
        "title_en": "Other — DAO, CPK, LDH, coagulation, lactose tolerance",
        "title_pt": "Outros — DAO, CPK, LDH, coagulação, tolerância à lactose",
        "subtitle_en": "Histamine intolerance workup and miscellaneous markers",
        "subtitle_pt": "Investigação de intolerância à histamina e marcadores diversos",
        "markers": [
          {
            "marker_en": "Diamine oxidase (DAO)",
            "marker_pt": "Diamina oxidase (DAO)",
            "unit": "U/mL",
            "ref_low": 3.74,
            "ref_high": 12.54,
            "ref_text_en": "< 3.74 = low histamine-degrading capacity   |   3.74 – 12.54 = moderate   |   > 12.54 = high",
            "ref_text_pt": "< 3,74 = baixa capacidade   |   3,74 a 12,54 = moderada   |   > 12,54 = alta",
            "points": [
              {
                "date": "2026-03-27",
                "value": 6.99,
                "note_en": "Moderate degrading capacity (55 HDU) — possible histamine intolerance",
                "note_pt": "Capacidade moderada (55 HDU) — possível intolerância à histamina"
              }
            ]
          },
          {
            "marker_en": "CPK (creatine kinase)",
            "marker_pt": "CPK (creatina fosfoquinase)",
            "unit": "U/L",
            "ref_low": null,
            "ref_high": 170,
            "ref_text_en": "Women: < 170 U/L",
            "ref_text_pt": "Mulheres: < 170 U/L",
            "points": [
              {
                "date": "2023-02-16",
                "value": 98
              }
            ]
          },
          {
            "marker_en": "LDH",
            "marker_pt": "Desidrogenase láctica (LDH)",
            "unit": "U/L",
            "ref_low": null,
            "ref_high": 250,
            "ref_text_en": "Adults: up to 250 U/L",
            "ref_text_pt": "Adultos: até 250 U/L",
            "points": [
              {
                "date": "2023-02-16",
                "value": 214
              }
            ]
          },
          {
            "marker_en": "INR (prothrombin)",
            "marker_pt": "INR (protrombina)",
            "unit": "",
            "ref_low": null,
            "ref_high": 1.3,
            "ref_text_en": "Normal: up to 1.30",
            "ref_text_pt": "Normal: até 1,30",
            "points": [
              {
                "date": "2024-07-24",
                "value": 0.92
              }
            ]
          },
          {
            "marker_en": "aPTT (patient/control)",
            "marker_pt": "TTPa (paciente / controle)",
            "unit": "s",
            "ref_low": 28,
            "ref_high": 40,
            "ref_text_en": "Reference: 28 – 40 seconds",
            "ref_text_pt": "Referência: 28 a 40 segundos",
            "points": [
              {
                "date": "2024-07-24",
                "value": 27.1,
                "flag": "L"
              }
            ]
          },
          {
            "marker_en": "Lactose tolerance (Δ glucose)",
            "marker_pt": "Curva de glicose (lactose) — Δ basal→pico",
            "unit": "mg/dL",
            "ref_low": 30,
            "ref_high": null,
            "ref_text_en": "Normal: > 30 mg/dL rise   |   Inconclusive: 20 – 30   |   Abnormal: < 20",
            "ref_text_pt": "Normal: aumento > 30 mg/dL   |   Inconclusivo: 20 a 30   |   Anormal: < 20",
            "points": [
              {
                "date": "2022-04-12",
                "value": 18.5,
                "flag": "L",
                "note_en": "Basal 80.9 → peak 99.4 mg/dL (Δ 18.5) — flat curve, suggests lactase deficiency",
                "note_pt": "Basal 80,9 → pico 99,4 mg/dL (Δ 18,5) — curva plana, sugestivo de deficiência de lactase"
              }
            ]
          }
        ]
      }
    ]
  },
  "inbody": {
    "device": "InBody120",
    "test_id": "191125-1",
    "date": "2026-02-11",
    "height_cm": 162,
    "age": 58,
    "sex": "female",
    "nutritionist": "Nutr. Ricardo Moretto",
    "crn": "CRN-3 63704",
    "score": 61,
    "composition": [
      {
        "marker_en": "Total Body Water",
        "marker_pt": "Água Corporal Total",
        "value": 29.8,
        "unit": "L",
        "ref_low": 28.1,
        "ref_high": 34.3
      },
      {
        "marker_en": "Protein",
        "marker_pt": "Proteína",
        "value": 7.9,
        "unit": "kg",
        "ref_low": 7.4,
        "ref_high": 9.1
      },
      {
        "marker_en": "Minerals",
        "marker_pt": "Minerais",
        "value": 2.99,
        "unit": "kg",
        "ref_low": 2.6,
        "ref_high": 3.17
      },
      {
        "marker_en": "Body Fat Mass",
        "marker_pt": "Massa de Gordura",
        "value": 29.4,
        "unit": "kg",
        "ref_low": 11.8,
        "ref_high": 17.6
      },
      {
        "marker_en": "Weight",
        "marker_pt": "Peso",
        "value": 70.1,
        "unit": "kg",
        "ref_low": 46.9,
        "ref_high": 63.4
      }
    ],
    "muscle_fat": [
      {
        "marker_en": "Weight",
        "marker_pt": "Peso",
        "value": 70.1,
        "unit": "kg",
        "ref_low": 46.9,
        "ref_high": 63.4
      },
      {
        "marker_en": "Skeletal Muscle Mass",
        "marker_pt": "Massa Muscular Esquelética",
        "value": 22,
        "unit": "kg",
        "ref_low": 17.3,
        "ref_high": 21.1
      },
      {
        "marker_en": "Body Fat Mass",
        "marker_pt": "Massa de Gordura",
        "value": 29.4,
        "unit": "kg",
        "ref_low": 11.8,
        "ref_high": 17.6
      }
    ],
    "obesity": [
      {
        "marker_en": "BMI",
        "marker_pt": "IMC",
        "value": 26.7,
        "unit": "kg/m²",
        "ref_low": 18.5,
        "ref_high": 25
      },
      {
        "marker_en": "Body Fat Percentage",
        "marker_pt": "PGC",
        "value": 41.9,
        "unit": "%",
        "ref_low": 18,
        "ref_high": 28
      }
    ],
    "lean_segmental": [
      {
        "limb": "left_arm",
        "label_pt": "Braço Esquerdo",
        "label_en": "Left arm",
        "kg": 2.13,
        "pct": 110.7,
        "status": "normal"
      },
      {
        "limb": "right_arm",
        "label_pt": "Braço Direito",
        "label_en": "Right arm",
        "kg": 2.11,
        "pct": 109.8,
        "status": "normal"
      },
      {
        "limb": "trunk",
        "label_pt": "Tronco",
        "label_en": "Trunk",
        "kg": 19.2,
        "pct": 91.6,
        "status": "normal"
      },
      {
        "limb": "left_leg",
        "label_pt": "Perna Esquerda",
        "label_en": "Left leg",
        "kg": 5.84,
        "pct": 81.3,
        "status": "below"
      },
      {
        "limb": "right_leg",
        "label_pt": "Perna Direita",
        "label_en": "Right leg",
        "kg": 5.78,
        "pct": 80.3,
        "status": "below"
      }
    ],
    "fat_segmental": [
      {
        "limb": "left_arm",
        "label_pt": "Braço Esquerdo",
        "label_en": "Left arm",
        "kg": 2.4,
        "pct": 254,
        "status": "above"
      },
      {
        "limb": "right_arm",
        "label_pt": "Braço Direito",
        "label_en": "Right arm",
        "kg": 2.3,
        "pct": 253.6,
        "status": "above"
      },
      {
        "limb": "trunk",
        "label_pt": "Tronco",
        "label_en": "Trunk",
        "kg": 15.6,
        "pct": 301.5,
        "status": "above"
      },
      {
        "limb": "left_leg",
        "label_pt": "Perna Esquerda",
        "label_en": "Left leg",
        "kg": 3.9,
        "pct": 166.3,
        "status": "above"
      },
      {
        "limb": "right_leg",
        "label_pt": "Perna Direita",
        "label_en": "Right leg",
        "kg": 3.9,
        "pct": 166.3,
        "status": "above"
      }
    ],
    "history": [
      {
        "date": "2025-11-18",
        "weight": 69.3,
        "smm": 21.1,
        "pbf": 43.5
      },
      {
        "date": "2026-02-11",
        "weight": 70.1,
        "smm": 22,
        "pbf": 41.9
      }
    ],
    "additional": {
      "basal_metabolic_rate": {
        "value": 1249,
        "unit": "kcal",
        "ref_low": 1419,
        "ref_high": 1652
      },
      "visceral_fat_level": {
        "value": 13,
        "unit": null,
        "ref_low": 1,
        "ref_high": 9
      },
      "obesity_degree": {
        "value": 127,
        "unit": "%",
        "ref_low": 90,
        "ref_high": 110
      }
    }
  }
};
